#!/usr/bin/env bash

# Switch colors.
osascript << EOF
tell application "System Events"
    tell appearance preferences
        set dark mode to not dark mode
    end tell
end tell
EOF

# Refresh wallpaper.
osascript << EOF
tell application "System Events"
    set currentWall to picture of current desktop
    set picture of current desktop to currentWall
EOF
